//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoApi
    {
        public int InfoApiId { get; set; }
        public string Token { get; set; }
        public Nullable<int> TypeAPI { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserIdApi { get; set; }
        public string Container { get; set; }
    
        public virtual User User { get; set; }
    }
}
